<?php

return [
    'name' => 'FastAdmin',
    'beian' => '',
    'cdnurl' => '',
    'version' => '1.0.1',
    'timezone' => 'Asia/Shanghai',
    'forbiddenip' => '',
    'languages' => [
    ],
    'fixedpage' => 'dashboard',
    'categorytype' => [
        'default' => 'Default',
        'page' => 'Page',
        'article' => 'Article',
        'test' => 'Test',
    ],
    'configgroup' => [
        'basic' => 'Basic',
        'email' => 'Email',
        'dictionary' => 'Dictionary',
        'user' => 'User',
        'example' => 'Example',
    ],
    'mail_type' => '1',
    'mail_smtp_host' => 'smtp.qq.com',
    'mail_smtp_port' => '465',
    'mail_smtp_user' => '10000',
    'mail_smtp_pass' => 'password',
    'mail_verify_type' => '2',
    'mail_from' => '10000@qq.com',
    'login_background' => '/assets/img/qrcode.png',
    'top10' => [
        '固特异' => '13.0',
        '米其林' => '9.5',
        '普利司通 ' => '8.0',
        '凡世通' => '7.5',
        '固铂' => '5.5',
        '百路驰' => '5.0',
        '韩泰' => '4.5',
        '马牌' => '4.0',
        '优科豪马' => '4.0',
        '飞劲' => '3.0',
    ],
    'whole' => '300',
    'single' => '200',
];